version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - selenium-hub
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
